<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'admin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'tcms_online');
define('DB_TABLE_PREFIX', '');
define('VERSION', ' (1.0) ');
?>
